### ISSUE TITLE
enable selectively

### ISSUE THREAD

**Issue by nickdesaulniers** [vivien/vim-linux-coding-style#10]
This might be a stupid question, but I'm looking to only enable this selectively.  The statement in the README seems to say this is possible:

> If you want to enable the coding style on demand without checking the filetype, you can use the :LinuxCodingStyle command.

But it seems that with this plugin installed, it's always enabled for C files.

It's also not clear to me what's meant by `on demand`.  Every file? Only when explicitly run?

> nnoremap <silent> <leader>a :LinuxCodingStyle<cr>

regardless of setting this, having the plugin seems to always affect my *.c files.

Is it possible that something else in my [~/.vimrc](https://github.com/nickdesaulniers/dotfiles/blob/master/.vimrc) could be conflicting with this?

**Comment by vivien** [comment]
Hi @nickdesaulniers, sorry for the late reply...

You can define an array of patterns in your vimrc and these options will be applied only if the buffer's path matches one of the pattern.

Put `let g:linuxsty_patterns = [ "/linux/", "/kernel/" ]` in your vimrc to apply options only if "/linux/" or "/kernel" is in buffer's path.

**Comment by nickdesaulniers** [comment]
great, thank!
