### ISSUE TITLE
linuxsty_patterns variable doesn't work

### ISSUE THREAD

**Issue by joe-skb7** [vivien/vim-linux-coding-style#6]
Consider next use-case (must be pretty common, I guess).

In my `~/.vimrc` I have:

    nnoremap <silent> <leader>a :LinuxCodingStyle<cr>
    let g:linuxsty_patterns = [ "/linux-omap" ]

When I'm in my kernel sources root dir (`~/some/path/linux-omap`), I open some source file:

    vim drivers/gpio/gpio-max732x.c

I see that plugin wasn't loaded automatically (e.g. `u8` type is not highlighted), although `linuxsty_patterns` was declared. But when pressing `\a`, plugin is loaded.

So it seems like `linuxsty_patterns` doesn't work as expected. I tried different masks, but no success.

While at it, it would be nice to be able to specify path masks, like:

    let g:linuxsty_patterns = [ "/*linux-*/" ]

**Comment by vivien** [comment]
Hi @joe-skb7,

Or you using Pathogen or something like that? I suspect that your syntax is off. Can you verify the `syntax on` line in your vimrc? For example, highlighting for `u8` wasn't working for me neither before because I was using Pathogen and `vim-sensible`. I got rid of this plugin and explicitly added at the top of my vimrc:
````
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect('bundle/{}', '~/Projects/vim/bundle/{}')
syntax on
filetype plugin indent on
````
and things work as expected.

For the patterns, it is already handled as a regexp. Try with `.*` instead of `*`:

    let g:linuxsty_patterns = [ "/.*linux-.*/" ]

**Comment by joe-skb7** [comment]
Yes, I'm using pathogen. But I **do** have `syntax on` and `filetype plugin indent on` in my `~/.vimrc` after running `pathogen#infect`. Executing pathogen as you propose didn't help neither.

**Comment by joe-skb7** [comment]
Indeed.It is [file-line](https://github.com/bogado/file-line) plugin. And I even found one particular commit which breaks this: [here](https://github.com/bogado/file-line/commit/f74d3f550ccef194ab617abb7de298ba900b44c0)

**Comment by joe-skb7** [comment]
Added issue for `file-line` plugin: [#64](https://github.com/bogado/file-line/issues/64)

**Comment by joe-skb7** [comment]
Hehe, I even figured seemed to be correct solution. They forgot to do

    doautocmd FileType

after

    doautocmd Syntax

Gonna send them patch for it.

**Comment by d-k-c** [comment]
Good catch @joe-skb7 , maybe we can find a way to make linux-coding-style more resilient to that kind of thing ?

Also, did you get a chance to test the pattern @vivien suggested ? It's not clear from the readme that it is possible, but it should already work.

**Comment by joe-skb7** [comment]
> maybe we can find a way to make linux-coding-style more resilient to that kind of thing ?

@d-k-c I think it would be rather redundant. We can't predict all possible interfering from other plugins, so the right policy (from my point of view) would be fixing issues in place where they came from.

> Also, did you get a chance to test the pattern @vivien suggested 

@d-k-c Yes, this plugin works fine, and templates work fine. I even did a little debugging and saw that all templates were handled and correct one was found, and plugin was automatically enabled (because of template match). There are no problems here. Problem was only in `file-line`, but now my patch is merged.

**Comment by joe-skb7** [comment]
Please close this as resolved, it was open by mistake.
